name: 🔗 GHA
on: [push, pull_request, merge_group]

concurrency:
  group: ${{ github.workflow }}|${{ github.ref_name }}
  cancel-in-progress: true

jobs:

  # First stage: Run static checks on all platforms.
  android-build:
    if: false
    name: 🤖 Android
    uses: ./.github/workflows/android_builds.yml

  ios-build:
    if: false
    name: 🍏 iOS
    uses: ./.github/workflows/ios_builds.yml

  linux-build:
    if: false
    name: 🐧 Linux
    uses: ./.github/workflows/linux_builds.yml

  macos-build:
    name: 🍎 macOS
    uses: ./.github/workflows/macos_builds.yml

  windows-build:
    name: 🏁 Windows
    uses: ./.github/workflows/windows_builds.yml

  web-build:
    if: false
    name: 🌐 Web
    uses: ./.github/workflows/web_builds.yml
